/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedCropDoctorRouteImport } from './routes/_authenticated/crop-doctor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNdviRouteImport } from './routes/_authenticated/ndvi'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedFarmIndexRouteImport } from './routes/_authenticated/farm.index'
import { Route as AuthenticatedFarmNewRouteImport } from './routes/_authenticated/farm.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCropDoctorRoute = AuthenticatedCropDoctorRouteImport.update({
  id: '/crop-doctor',
  path: '/crop-doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNdviRoute = AuthenticatedNdviRouteImport.update({
  id: '/ndvi',
  path: '/ndvi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmIndexRoute = AuthenticatedFarmIndexRouteImport.update({
  id: '/farm/',
  path: '/farm/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmNewRoute = AuthenticatedFarmNewRouteImport.update({
  id: '/farm/new',
  path: '/farm/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/crop-doctor': typeof AuthenticatedCropDoctorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ndvi': typeof AuthenticatedNdviRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/farm/new': typeof AuthenticatedFarmNewRoute
  '/farm/': typeof AuthenticatedFarmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/crop-doctor': typeof AuthenticatedCropDoctorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ndvi': typeof AuthenticatedNdviRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/farm/new': typeof AuthenticatedFarmNewRoute
  '/farm': typeof AuthenticatedFarmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/crop-doctor': typeof AuthenticatedCropDoctorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ndvi': typeof AuthenticatedNdviRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/_authenticated/farm/new': typeof AuthenticatedFarmNewRoute
  '/_authenticated/farm/': typeof AuthenticatedFarmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/crop-doctor'
    | '/dashboard'
    | '/ndvi'
    | '/weather'
    | '/farm/new'
    | '/farm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/crop-doctor'
    | '/dashboard'
    | '/ndvi'
    | '/weather'
    | '/farm/new'
    | '/farm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/crop-doctor'
    | '/_authenticated/dashboard'
    | '/_authenticated/ndvi'
    | '/_authenticated/weather'
    | '/_authenticated/farm/new'
    | '/_authenticated/farm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crop-doctor': {
      id: '/_authenticated/crop-doctor'
      path: '/crop-doctor'
      fullPath: '/crop-doctor'
      preLoaderRoute: typeof AuthenticatedCropDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ndvi': {
      id: '/_authenticated/ndvi'
      path: '/ndvi'
      fullPath: '/ndvi'
      preLoaderRoute: typeof AuthenticatedNdviRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm/': {
      id: '/_authenticated/farm/'
      path: '/farm'
      fullPath: '/farm/'
      preLoaderRoute: typeof AuthenticatedFarmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm/new': {
      id: '/_authenticated/farm/new'
      path: '/farm/new'
      fullPath: '/farm/new'
      preLoaderRoute: typeof AuthenticatedFarmNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedCropDoctorRoute: typeof AuthenticatedCropDoctorRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNdviRoute: typeof AuthenticatedNdviRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
  AuthenticatedFarmNewRoute: typeof AuthenticatedFarmNewRoute
  AuthenticatedFarmIndexRoute: typeof AuthenticatedFarmIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedCropDoctorRoute: AuthenticatedCropDoctorRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNdviRoute: AuthenticatedNdviRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
  AuthenticatedFarmNewRoute: AuthenticatedFarmNewRoute,
  AuthenticatedFarmIndexRoute: AuthenticatedFarmIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
